- name: condition
  hosts: localhost
  become: yes
  tasks:
   - name: creating output
     ansible.builtin.command: roboshop
     register: aru
   - name: checking output
     ansible.builtin.debug:
      msg: "output: {{aru}}"
   - name: check return code and exit status
     ansible.builtin.debug:
      msg: "status:{{aru.rc}}"
   - name: create user
     ansible.builtin.user:
      name: roboshop
     when: aru.rc != 0

