- name: variables from play level
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: finding variables
    ansible.builtin.debug:
     msg: "Hi,I am learning {{course}} the trainer is {{trainer}} and the duration is {{duration}}"