- name: variables from play level
  hosts: localhost
  vars:
   course: "DevOps"
   trainer: "Siva"
   duration: "110HRS"
  tasks:
    course: "DevOps with AWS"
    ansible.builtin.debug:
     msg: "Hi,i am learning {{course}} the trainer is {{trainer}} and the duration is {{duration}}"